### ISSUE TITLE
In-line images

### ISSUE THREAD

**Issue by xiejia1995** [hcts-hra/ecpo-data#128]
<img width="347" alt="2022-02-25 12_54_15-" src="https://user-images.githubusercontent.com/76219575/155712485-bd711a72-a0d8-457e-9005-506f27c73431.png">
(1920-04-21_0002)
how do we deal with the in-line images? @duncdrum @MatthiasArnold 

do we type`<image unit="char" extent="2"/>`?

**Comment by duncdrum** [comment]
so far we don't have a way to encode inline images, for now this would be two gaiji

**Comment by duncdrum** [comment]
There is an important distinction here. An article that contains a graphic or figure, that's what properly nested `<div type="image" itemID="aaa"/>` is for. And images that appear as inline characters, that's what `&#xe111;` is for.

**Comment by duncdrum** [comment]
closed by #155
