### ISSUE TITLE
add missing ECPO ids to items in Groundtruth

### ISSUE THREAD

**Issue by duncdrum** [hcts-hra/ecpo-data#146]
Items need ids :-)

**Comment by xiejia1995** [comment]
current status:

**Comment by xiejia1995** [comment]
p.s. for the meeting 13th Sept. 
1. https://kjc-sv034.kjc.uni-heidelberg.de/ecpo/admin/article/article_edit.php?magazin_id=1&issue_id=20&article_id=328

**Comment by JoeTo1** [comment]
is there any action from me required?

**Comment by duncdrum** [comment]
@xiejia1995 
1. use article id with type article
2. …
3. add `no_caption`

@JoeTo1 no nothing so far

**Comment by duncdrum** [comment]
@xiejia1995 see #9 and #25 

as the last one was closed in 2021 @JoeTo1  I assume the new IDs are in place?

**Comment by duncdrum** [comment]
closed by #155
