### ISSUE TITLE
Issues of Jingbao 1930-04 and 1920-04

### ISSUE THREAD

**Issue by xiejia1995** [hcts-hra/ecpo-data#79]
here we will post our new findings of jingbao 1930-04

**Comment by xiejia1995** [comment]
1. as the pic shows, the heading part of 1930-04 is different from 1939. 
<img width="612" alt="2021-09-29 17_15_03-jb_1324_1930-04-06_0001+0004 jpg ‎- heading" src="https://user-images.githubusercontent.com/76219575/135298151-2f7c09f4-37ae-49ea-a760-537b897ba902.png">
i suggest that we define the type of the top margin as "margin", while the big characters "晶報" and the surroundings as "head".
`<div type="margin" mode="horizontal-tb" dir="rtl">
            <div>
                民國十九年四月六日<lb/>
            </div>
            <div>
                星期日<lb/>
            </div>
            <div  mode="vertical-lr" dir="ltr">
                The　Crystal<lb/>
            </div>
            <div  mode="vertical-lr" dir="ltr">
                ESTABLISHED　1919<lb/>
            </div>
        </div>
        <div type="advert">
            <div mode="horizontal-tb" dir="rtl">
                定報價格<lb/>
            </div>
            <div>
                每三日出一張增刊無定<lb/>
                中國境内全年二元半年一元一<lb/>
                角每月二角日本同其餘外國各<lb/>
                埠加倍均作大洋計算報資先惠<lb/>
                郵費在内郵票加一<lb/>
            </div>
        </div>
        <div type="other">
                今日一張零售大洋二分四釐<lb/> 
        </div>
        <div type="head" dir="rtl" mode="horizontal-tb">
            <div>
                晶報<lb/>
            </div>
            <div>
                自動電話一二四二八號<lb/> 
            </div>
            <div>
                電報掛號四三七七卽神字<lb/> 
            </div>
        </div>
        <div type="advert">
                第一千三百廿三號<lb/> 
        </div>
        <div type="advert">
            <div type="other" mode="horizontal-tb" dir="rtl">
                廣吿刊例<lb/>
            </div> 
            <div>
                『新聞欄中』價面議『新聞中縫』<lb/> 
                計三十字長十字寬爲一格以半<lb/> 
                格起碼每期每格洋八元『封面<lb/>
                中縫』分格等與新聞中縫同每<lb/>
                期每格洋五元『封面』計十五字<lb/>
                高十九字寬爲一格以半格起碼<lb/>
                每期每格洋六元『後幅』分格等<lb/>
                與封面同每期每格洋五元<lb/>               
            </div>
        </div>`

what do you think of it?

**Comment by xiejia1995** [comment]
@konstantinhenke hi, konstantin, i update the process of the 1930-04 groundtruth in this google spreadsheet: (https://docs.google.com/spreadsheets/d/1wRHglbc5szTPdn_QIV5pcV4IP7lBuQfMof9feusIOHg/edit?usp=sharing)

so you can have an idea of the whole process of our typing work.

**Comment by konstantinhenke** [comment]
hi xie jia, thank you, I sent you a request to access the spreadsheet.

**Comment by xiejia1995** [comment]
@MatthiasArnold @konstantinhenke 
shall we comment on this case: the last character on the right side is not well aligned.
![2022-01-18 10_52_32-jb_1328_1930-04-18_0002+0003 jpg ‎- Fotos](https://user-images.githubusercontent.com/76219575/149914144-0982f26e-96cf-495b-a304-1dba9bb5c7b3.png)
(jb_1328_1930-04-18_0002+0003)

**Comment by duncdrum** [comment]
@xiejia1995 the structure here is invalid, and introduces line-breaks where there are none.

```xml
    <div type="margin" mode="horizontal-tb" dir="rtl">
        <p>
            民國十九年四月三日　星期四
            <lb />
        </p>
        <p mode="horizontal-tb" dir="ltr">
            The　Crystal　 ESTABLISHED　1919
            <lb />
        </p>
    </div>
    <div type="advert">
        <p mode="horizontal-tb" dir="rtl">
            定報價格
            <lb />
        </p>
        <p>
            每三日出一張增刊無定
            <lb />
            中國境內全年二元半年一元一
            <lb />
            角每月二角日本同其餘外國各
            <lb />
            埠加倍均作大洋計算報資先惠
            <lb />
            郵費在內郵票加一
            <lb />
        </p>
    </div>
    <div type="other">
        <p>
            今日一張零售大洋二分四釐
            <lb />
        </p>
    </div>
    <div type="head" dir="rtl" mode="horizontal-tb">
        <p>
            晶報
            <lb />
        </p>
        <p>
            ◘自動電話一二四二八號◘
            <lb />
            ◘電報掛號四三七七卽神字◘
            <lb />
        </p>
    </div>
    <div type="other">
        <p>
            第一千三百廿三號
            <lb />
        </p>
    </div>
    <div type="advert">
        <p mode="horizontal-tb" dir="rtl">
            廣吿刊例
            <lb />
        </p>
        <p>
            『新聞欄中』價面議『新聞中縫』
            <lb />
            計三十字長十字寬爲一格以半
            <lb />
            格起碼每期每格洋八元『封面
            <lb />
            中縫』分格等與新聞中縫同每
            <lb />
            期每格洋五元『封面』計十五字
            <lb />
            高十九字寬爲一格以半格起碼
            <lb />
            每期每格洋六元『後幅』分格等
            <lb />
            與封面同每期每格洋五元
            <lb />
        </p>
    </div>
```
